version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP protocol (used by your code)
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: fastapi
      RABBITMQ_DEFAULT_PASS: fastapi
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
